### PR TITLE
Fix compilation error in ./test/

### PR DESCRIPTION
**Pull request by phil9909**
We noticed that `go test ./test/` failed with a compilation error:

```                                                                                                                                                      
# github.com/pivotal/kpack/test [github.com/pivotal/kpack/test.test]                                                                                                                           
test/execute_build_test.go:218:5: unknown field 'ServiceAccount' in struct literal of type "github.com/pivotal/kpack/pkg/apis/build/v1alpha2".NamespacedBuilderSpec                            
```

**Note:**
Maybe you should consider at least compiling the e2e tests in the CI.
This can be done with:

```bash
go test -c -o /tmp/test-bin ./test/
```

### CODE REVIEW

**Comment by phil9909** [comment]
Probably introduced by #861, therefore mentioning @matthewmcnew
